version: '3.8'

services:
  treatment_evaluation_service:
    build:
      context: .
      dockerfile: treatment_evaluation/docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - local.env

  criteria_store_service:
    build:
      context: .
      dockerfile: criteria_store/docker/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - local.env
